branch-defaults:
  default:
    environment: bfm-test
    group_suffix: null
environment-defaults:
  beautyforme-website:
    branch: null
    repository: null
  bfm-test:
    branch: null
    repository: null
global:
  application_name: beautyforme-test
  branch: null
  default_ec2_keyname: beautyforme-eb
  default_platform: arn:aws:elasticbeanstalk:us-west-2::platform/Python 3.6 running
    on 64bit Amazon Linux/2.9.2
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
